services:
  miniapp:
    build: .
    container_name: unifyimages_miniapp
    network_mode: host
    restart: unless-stopped
    environment:
      - PORT=3000
    env_file:
      - ../.env
    volumes:
      - ../data:/data
    # Opcional: Se quiser montar os arquivos estáticos sem precisar buildar o docker toda hora na fase de testes:
    # volumes:
    #   - ./public:/app/public

  # Exemplo de configuração do Cloudflare Tunnel (se você não rodar ele externamente)
  # cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   command: tunnel run
  #   environment:
  #     - TUNNEL_TOKEN=seu_token_aqui
